version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongodb
    versions:
    - 3.6.6
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
  - dependency-name: bluebird
    versions:
    - 3.7.2
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.3.5
  - dependency-name: "@forestadmin/devops"
    versions:
    - 3.0.3
  - dependency-name: inquirer
    versions:
    - 8.0.0
  - dependency-name: eslint-plugin-sonarjs
    versions:
    - 0.6.0
  - dependency-name: sequelize
    versions:
    - 6.6.2
  - dependency-name: simple-git
    versions:
    - 2.37.0
  - dependency-name: rimraf
    versions:
    - 3.0.2
  - dependency-name: scratch-svg-renderer
    versions:
    - 0.2.0-prerelease.20210317184701
    - 0.2.0-prerelease.20210325225314
    - 0.2.0-prerelease.20210408171934
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
  - dependency-name: lodash.defaultsdeep
    versions:
    - 4.6.1
  - dependency-name: omggif
    versions:
    - 1.0.10
  - dependency-name: webpack-cli
    versions:
    - 4.6.0
  - dependency-name: react-ga
    versions:
    - 3.3.0
  - dependency-name: papaparse
    versions:
    - 5.3.0
  - dependency-name: react-contextmenu
    versions:
    - 2.14.0
  - dependency-name: lodash.throttle
    versions:
    - 4.1.1
  - dependency-name: scratch-audio
    versions:
    - 0.1.0-prerelease.20200528195344
  - dependency-name: enzyme-adapter-react-16
    versions:
    - 1.15.6
  - dependency-name: react-modal
    versions:
    - 3.12.1
  - dependency-name: react-tabs
    versions:
    - 3.2.1
  - dependency-name: ws
    versions:
    - 7.4.4
  - dependency-name: react-dom
    versions:
    - 16.13.0
  - dependency-name: scratch-storage
    versions:
    - 1.3.3
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: js-yaml
    versions:
    - 3.14.1
  - dependency-name: mixin-deep
    versions:
    - 1.3.2
  - dependency-name: handlebars
    versions:
    - 4.7.7
  - dependency-name: lodash-es
    versions:
    - 4.17.21
  - dependency-name: webpack-dev-server
    versions:
    - 3.1.11
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: gh-pages
    versions:
    - 3.1.0
  - dependency-name: three
    versions:
    - 0.126.1
  - dependency-name: react-router
    versions:
    - 5.2.0
  - dependency-name: react-scripts
    versions:
    - 3.2.0
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  - dependency-name: elliptic
    versions:
    - 6.5.4
